WITH RECURSIVE CTE_ECOLI AS (
    
    SELECT ID, PARENT_ID, 1 AS level
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, C.level+1 AS level
    FROM ECOLI_DATA AS E
    JOIN CTE_ECOLI C ON E.PARENT_ID = C.ID 
)

SELECT COUNT(*) AS COUNT, c.level AS GENERATION
FROM CTE_ECOLI c
LEFT JOIN ECOLI_DATA d ON c.ID = d.PARENT_ID 
WHERE d.ID IS NULL
GROUP BY c.level
ORDER BY c.level