SELECT COUNT(FI.FISH_TYPE) AS FISH_COUNT
FROM FISH_INFO AS FI 
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.FISH_TYPE IN (
    SELECT FN.FISH_TYPE
    FROM FISH_NAME_INFO AS FN
    WHERE FN.FISH_NAME IN ('BASS','SNAPPER')
)
